In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
independent.shape

(399, 27)

In [9]:
dependent=dataset[['classification_yes']]

In [10]:
dependent.shape

(399, 1)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
scalar= StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [13]:
from sklearn.svm import SVC

In [14]:
from sklearn.model_selection import GridSearchCV
param_grid ={'kernel':['linear','rbf','poly','sigmoid'],'gamma':['auto','scale'],'C':[10.100,1000,2000,3000]}
grid = GridSearchCV(SVC(probability=True), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10.1, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [15]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, grid_predictions)

In [16]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10.1, 'gamma': 'auto', 'kernel': 'sigmoid'}: 0.9924946382275899

In [17]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [18]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

1.0

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.022271,0.004773,0.028762,0.008351,10.1,auto,linear,"{'C': 10.1, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,19
1,0.024513,0.002182,0.029478,0.006508,10.1,auto,rbf,"{'C': 10.1, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,1.000000,1.000000,0.988859,0.014751,4
2,0.033265,0.004533,0.026637,0.004852,10.1,auto,poly,"{'C': 10.1, 'gamma': 'auto', 'kernel': 'poly'}",1.000000,0.981014,1.000000,1.000000,0.981217,0.992446,0.009252,3
3,0.016018,0.002663,0.026349,0.005133,10.1,auto,sigmoid,"{'C': 10.1, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,1.000000,1.000000,0.981031,1.000000,0.992520,0.009163,1
4,0.014290,0.002054,0.027698,0.007334,10.1,scale,linear,"{'C': 10.1, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,19
5,0.022102,0.002285,0.028704,0.005682,10.1,scale,rbf,"{'C': 10.1, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,1.000000,1.000000,0.988859,0.014751,4
6,0.035131,0.003629,0.025607,0.002998,10.1,scale,poly,"{'C': 10.1, 'gamma': 'scale', 'kernel': 'poly'}",1.000000,0.981014,1.000000,0.981031,0.981217,0.988652,0.009266,6
7,0.018439,0.003840,0.028832,0.003170,10.1,scale,sigmoid,"{'C': 10.1, 'gamma': 'scale', 'kernel': 'sigmo...",0.981569,1.000000,1.000000,0.981031,1.000000,0.992520,0.009163,1
8,0.018066,0.006173,0.024623,0.001401,1000.0,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,19
9,0.019526,0.004657,0.033745,0.004635,1000.0,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,7
10,0.032861,0.005631,0.026648,0.003295,1000.0,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,13
11,0.020325,0.003635,0.021942,0.001331,1000.0,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,27
12,0.016702,0.000999,0.022002,0.003106,1000.0,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,19
13,0.019427,0.006386,0.019056,0.001970,1000.0,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,7
14,0.025939,0.004900,0.022806,0.002268,1000.0,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,13
15,0.013252,0.003194,0.020685,0.002975,1000.0,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,27
16,0.017278,0.004111,0.021075,0.003133,2000.0,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,19
17,0.019899,0.003901,0.027156,0.005991,2000.0,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,7
18,0.031775,0.003161,0.021294,0.001325,2000.0,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,13
19,0.015963,0.005874,0.021610,0.001366,2000.0,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,27
20,0.020645,0.006056,0.021220,0.001580,2000.0,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,19
21,0.014957,0.003778,0.021633,0.001556,2000.0,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,7
22,0.027200,0.002434,0.020788,0.002903,2000.0,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,13
23,0.018177,0.004293,0.018956,0.002473,2000.0,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,27
24,0.017534,0.002558,0.020033,0.002411,3000.0,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,19
25,0.015736,0.003596,0.023043,0.003555,3000.0,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,7
26,0.026166,0.005403,0.019728,0.002314,3000.0,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,13
27,0.014248,0.003114,0.018714,0.002031,3000.0,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,27
28,0.014229,0.003268,0.019705,0.002008,3000.0,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.981569,0.962636,0.962573,0.981031,0.981217,0.973805,0.009147,19
29,0.020982,0.004102,0.027294,0.003389,3000.0,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.963284,0.981014,1.000000,0.981031,1.000000,0.985066,0.013807,7
30,0.029987,0.006455,0.023745,0.004117,3000.0,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,13
31,0.015117,0.002260,0.019553,0.005009,3000.0,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,27

age = float(input("Age: "))
bp = float(input("BP: "))
sg = float(input("SG (1.010/1.015/1.020/1.025): "))
al = float(input("AL: "))
su = float(input("SU: "))

rbc = int(input("RBC normal=1, abnormal=0: "))
pc = int(input("PC normal=1, abnormal=0: "))
pcc = int(input("PCC present=1, notpresent=0: "))
ba = int(input("BA present=1, notpresent=0: "))

bgr = float(input("BGR: "))
bu = float(input("BU: "))
sc = float(input("SC: "))
sod = float(input("SOD: "))
pot = float(input("POT: "))
hrmo = float(input("HGB/Hemo: "))
pcv = float(input("PCV: "))
wc = float(input("WC: "))
rc = float(input("RC: "))

htn = int(input("HTN yes=1, no=0: "))
dm = int(input("DM yes=1, no=0: "))
cad = int(input("CAD yes=1, no=0: "))
appet = int(input("Appetite yes=1, no=0: "))
pe = int(input("PE yes=1, no=0: "))
ane = int(input("ANE yes=1, no=0: "))

In [24]:
# Manual Patient Input

age = 48
bp = 80
sg = 1.020
al = 1
su = 0

rbc = 1
pc = 1
pcc = 0
ba = 0

bgr = 121
bu = 36
sc = 1.2
sod = 138
pot = 4.5
hrmo = 15.4
pcv = 44
wc = 7800
rc = 5.2

htn = 1
dm = 0
cad = 0
appet = 1
pe = 0
ane = 0


# SG → Dummy Variables

sg_b = 1 if sg == 1.010 else 0
sg_c = 1 if sg == 1.015 else 0
sg_d = 1 if sg == 1.020 else 0
sg_e = 1 if sg == 1.025 else 0


# Create patient data
new_patient = [[
    age,
    bp,
    al,
    su,
    bgr,
    bu,
    sc,
    sod,
    pot,
    hrmo,
    pcv,
    wc,
    rc,
    sg_b,
    sg_c,
    sg_d,
    sg_e,
    rbc,
    pc,
    pcc,
    ba,
    htn,
    dm,
    cad,
    appet,
    pe,
    ane
]]


# Apply StandardScaler
preinput = scalar.transform(new_patient)


# Prediction
Future_Prediction = grid.predict(preinput)

print("Future_Prediction =", Future_Prediction)


# Result
if Future_Prediction[0] == 1:
    print("Result: CKD")
else:
    print("Result: NOT CKD")

Future_Prediction = [1]
Result: CKD

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [25]:
import pickle

# Save the trained GridSearch model
pickle.dump(grid, open("finalized_model_new_CKD.sav", "wb"))

# Save the StandardScaler
pickle.dump(scalar, open("scalar_CKD.sav", "wb"))

print("Model and Scalar saved successfully!")

Model and Scalar saved successfully!